### ISSUE TITLE
Schema URLs appear to have changed

### ISSUE THREAD

**Issue by selimnairb** [geojson/schema#29]
GeoJSON schema URLs (e.g., https://geojson.org/schema/MultiPolygon.json) appear to no longer resolve, resulting in a 404 error, and documents that can no longer validate. Is this intentional? Are there new URLs? Thanks.

**Comment by emmanuelmathot** [comment]
Same issue at https://schemas.stacspec.org/v1.0.0/item-spec/json-schema/item.json# with the reference to https://geojson.org/schema/Feature.json

**Comment by tschaub** [comment]
Apologies for this breakage.  Fixed with 660d67d1d44d168aa2bba3931fb23618b058d14b.
