### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by apiel** [geojson/schema#32]
Would it be possible to publish this package on NPM? And even better to have typescript support to it :-)

**Comment by haoliangyu** [comment]
Publishing on npm will be very helpful!

**Comment by romain-tracktik** [comment]
We would really need this on `npm` too. Currently we are thinking of different ways of adding JSON Schema validation to our data model : 
- downloading at build time the JSON Schema from this repo
- converting `turf` TS types into JSON Schema (with a script)
- using other user's repo that are exposing the JSON Schema

But none is optimal. A simple official npm package would be really nice to avoid having the schemas scattered across the community 🙏 
(cc @tschaub)

**Comment by tschaub** [comment]
@apiel  @haoliangyu @romain-tracktik - I've published https://www.npmjs.com/package/geojson-schema with the JSON schema files at the root of the package.  Let me know if anything else would be useful in the package.

**Comment by romain-tracktik** [comment]
Awesome, thank you for the fast action @tschaub 🙏
