### ISSUE TITLE
HTTPS for geojson.org

### ISSUE THREAD

**Issue by dereklieu** [geojson/schema#7]
Requesting a schema document, eg [http://geojson.org/schema/Feature.json](http://geojson.org/schema/Feature.json), results in a mixed-content error when the client script is served over https. Are there any plans to support https for geojson.org?

Thanks in advance.

**Comment by mojodna** [comment]
@tschaub any chance you can have a look at this?

GitHub presents a certificate, but with the wrong domain name, so it may be as simple as changing "Custom domain" in the repository settings:

![image](https://user-images.githubusercontent.com/45/57088201-9c154c80-6cb6-11e9-91d9-66da78bad682.png)

It might also be a DNS problem, if geojson.org isn't pointed to the current GH Pages IPs.

**Comment by tschaub** [comment]
Yes, this is clearly something that should be done.  For this to work, we need to update the A Records for geojson.org to:

- 185.199.108.153
- 185.199.109.153
- 185.199.110.153
- 185.199.111.153

We are currently using the old IP addresses (192.30.252.153 and 192.30.252.154) that predate GitHub's HTTPS support for custom domains.

I've reached out to @mpdaly, who I think has an account with our DNS provider, to ask if this can be updated.

**Comment by tschaub** [comment]
https://geojson.org/schema/GeoJSON.json
